# Generated by Django 5.1.1 on 2025-02-11 15:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import imagekit.models.fields
import network.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Access_Policies',
            fields=[
                ('access_policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_echo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('device_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EditedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', imagekit.models.fields.ProcessedImageField(unique=True, upload_to='object_storage/original_images/')),
                ('mask', models.ImageField(blank=True, null=True, upload_to='object_storage/masks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bbox_json', models.JSONField(blank=True, null=True)),
                ('validation_flag', models.BooleanField(default=False)),
                ('validation_flag_bbox', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('localization_id', models.AutoField(primary_key=True, serialize=False)),
                ('localization_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object_Metadata',
            fields=[
                ('object_metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('sex', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Processing_Types',
            fields=[
                ('processing_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('processing_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scaling_Value',
            fields=[
                ('scaling_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('scaling_value_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.AutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UploadZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(upload_to='zip_files/')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YandexCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='object_storage/')),
            ],
        ),
        migrations.CreateModel(
            name='ZipArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='archives/')),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('task', models.CharField(blank=True, max_length=50, null=True)),
                ('has_package', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=255)),
                ('label_properties', models.FileField(blank=True, null=True, upload_to=network.models.record_label_path)),
                ('access_policy_id', models.ForeignKey(db_column='access_policy_id', on_delete=django.db.models.deletion.CASCADE, to='network.access_policies')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_id', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, to='network.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='Access_Group_Linkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_policy_id', models.ForeignKey(db_column='access_policy_id', on_delete=django.db.models.deletion.CASCADE, to='network.access_policies')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='network.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata_Static',
            fields=[
                ('metadata_static_id', models.AutoField(primary_key=True, serialize=False)),
                ('arbitrary_data', models.FileField(blank=True, null=True, upload_to=network.models.record_metadata_path)),
                ('asset_structure', models.FileField(blank=True, null=True, upload_to=network.models.record_metadata_path)),
                ('device_type_id', models.ForeignKey(db_column='device_type_id', on_delete=django.db.models.deletion.CASCADE, to='network.device_type')),
                ('scaling_value_id', models.ForeignKey(db_column='scaling_value_id', on_delete=django.db.models.deletion.CASCADE, to='network.scaling_value')),
            ],
        ),
        migrations.AddField(
            model_name='datasets',
            name='metadata_static_id',
            field=models.ForeignKey(blank=True, db_column='metadata_static_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.metadata_static'),
        ),
        migrations.CreateModel(
            name='Assets_Metadata_Dynamic',
            fields=[
                ('asset_metadata_dynamic_id', models.AutoField(primary_key=True, serialize=False)),
                ('arbitrary_data_json_link', models.FileField(upload_to=network.models.record_dynamic_path)),
                ('asset_id', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, to='network.assets')),
                ('diagnosis_id', models.ForeignKey(db_column='diagnosis_id', on_delete=django.db.models.deletion.CASCADE, to='network.diagnosis')),
                ('localization_id', models.ForeignKey(db_column='localization_id', on_delete=django.db.models.deletion.CASCADE, to='network.localization')),
                ('object_metadata_id', models.ForeignKey(db_column='object_metadata_id', on_delete=django.db.models.deletion.CASCADE, to='network.object_metadata')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('package_status', models.CharField(max_length=255)),
                ('package', models.FileField(blank=True, null=True, upload_to=network.models.package_path)),
                ('dataset_id', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, to='network.datasets')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_link', models.FileField(upload_to=network.models.record_file_path)),
                ('validation_mask_flag', models.BooleanField(default=False)),
                ('validation_bbox_flag', models.BooleanField(default=False)),
                ('asset_id', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, to='network.assets')),
            ],
        ),
        migrations.CreateModel(
            name='Masks',
            fields=[
                ('mask_id', models.AutoField(primary_key=True, serialize=False)),
                ('mask_link', models.FileField(upload_to=network.models.record_mask_path)),
                ('record_id', models.ForeignKey(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.records')),
            ],
        ),
        migrations.CreateModel(
            name='Bounding_Boxes',
            fields=[
                ('bounding_box_id', models.AutoField(primary_key=True, serialize=False)),
                ('bounding_box_link', models.FileField(upload_to=network.models.record_bbox_path)),
                ('record_id', models.ForeignKey(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.records')),
            ],
        ),
        migrations.CreateModel(
            name='Group_User_Linkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='network.groups')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='network.roles')),
            ],
        ),
        migrations.AddField(
            model_name='object_metadata',
            name='species_id',
            field=models.ForeignKey(db_column='species_id', on_delete=django.db.models.deletion.CASCADE, to='network.species'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='FREE', max_length=50)),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
