# Generated by Django 5.1.1 on 2025-02-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masks',
            name='record_id',
        ),
        migrations.DeleteModel(
            name='Bounding_Boxes',
        ),
        migrations.DeleteModel(
            name='Masks',
        ),
    ]
