# Generated by Django 5.1.1 on 2025-02-11 15:11

import django.db.models.deletion
import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_masks_record_id_delete_bounding_boxes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounding_Boxes',
            fields=[
                ('record_metadata_dynamic_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_metadata_dynamic_link', models.FileField(blank=True, null=True, upload_to=network.models.record_metadata_dynamic_path)),
                ('processing_type_id', models.ForeignKey(blank=True, db_column='processing_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.processing_types')),
                ('record_id', models.ForeignKey(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.records')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Masks',
            fields=[
                ('record_metadata_dynamic_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_metadata_dynamic_link', models.FileField(blank=True, null=True, upload_to=network.models.record_metadata_dynamic_path)),
                ('processing_type_id', models.ForeignKey(blank=True, db_column='processing_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.processing_types')),
                ('record_id', models.ForeignKey(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.records')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
