# Generated by Django 5.1.1 on 2025-09-28 12:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import network.models.assets_metadata
import network.models.datasets
import network.models.metadata_static
import network.models.packages
import network.models.records
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Access_Types',
            fields=[
                ('access_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('device_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('diagnosis_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('localization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('localization_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object_Metadata',
            fields=[
                ('object_metadata_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processing_Types',
            fields=[
                ('processing_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('processing_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scaling_Value',
            fields=[
                ('scaling_value_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scaling_value_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('sex_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sex_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('species_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Access_Policies',
            fields=[
                ('access_policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_type_id', models.ForeignKey(db_column='access_type_id', on_delete=django.db.models.deletion.CASCADE, to='network.access_types')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('dataset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('label_properties', models.FileField(blank=True, null=True, upload_to=network.models.datasets.record_label_path)),
                ('metrics', models.FileField(blank=True, max_length=500, null=True, upload_to=network.models.datasets.dataset_metrics_path)),
                ('status', models.CharField(blank=True, default='FREE', max_length=50, null=True)),
                ('access_policy_id', models.ForeignKey(blank=True, db_column='access_policy_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.access_policies')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('metrics', models.FileField(blank=True, max_length=500, null=True, upload_to=network.models.datasets.asset_metrics_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_id', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, to='network.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadDataset',
            fields=[
                ('transfer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_files_expected', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('files_uploaded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('phase', models.CharField(choices=[('preparing', 'Preparing Files'), ('zipping', 'Creating Archive'), ('ready', 'Ready for Download'), ('copying', 'Copying Dataset')], default='preparing', max_length=20)),
                ('archive_file', models.FileField(blank=True, null=True, upload_to='dataset_archives/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dataset_id', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, to='network.datasets')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Access_Group_Linkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_policy_id', models.ForeignKey(db_column='access_policy_id', on_delete=django.db.models.deletion.CASCADE, to='network.access_policies')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='network.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata_Static',
            fields=[
                ('metadata_static_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arbitrary_data', models.FileField(blank=True, null=True, upload_to=network.models.metadata_static.record_metadata_path)),
                ('asset_structure', models.FileField(blank=True, null=True, upload_to=network.models.metadata_static.record_metadata_path)),
                ('scales', models.JSONField(blank=True, default=list, help_text="[{'barcode': 10, 'unit': 'nm', 'value_per_pixel': 0.5}]")),
                ('device_type_id', models.ForeignKey(blank=True, db_column='device_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.device_type')),
                ('scaling_value_id', models.ForeignKey(blank=True, db_column='scaling_value_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.scaling_value')),
            ],
        ),
        migrations.AddField(
            model_name='datasets',
            name='metadata_static_id',
            field=models.ForeignKey(blank=True, db_column='metadata_static_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.metadata_static'),
        ),
        migrations.CreateModel(
            name='Assets_Metadata_Dynamic',
            fields=[
                ('asset_metadata_dynamic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arbitrary_data_json_link', models.FileField(blank=True, null=True, upload_to=network.models.assets_metadata.record_dynamic_path)),
                ('asset_id', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, to='network.assets')),
                ('diagnosis_id', models.ForeignKey(blank=True, db_column='diagnosis_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.diagnosis')),
                ('localization_id', models.ForeignKey(blank=True, db_column='localization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.localization')),
                ('object_metadata_id', models.ForeignKey(blank=True, db_column='object_metadata_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.object_metadata')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('package_status', models.CharField(max_length=255)),
                ('package', models.FileField(blank=True, null=True, upload_to=network.models.packages.package_path)),
                ('label_properties', models.FileField(blank=True, null=True, upload_to=network.models.packages.record_label_path)),
                ('dataset_id', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, to='network.datasets')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_link', models.FileField(upload_to=network.models.records.record_file_path)),
                ('validation_mask_flag', models.BooleanField(default=False)),
                ('validation_bbox_flag', models.BooleanField(default=False)),
                ('description_mask', models.JSONField(blank=True, null=True)),
                ('description_bbox', models.JSONField(blank=True, null=True)),
                ('asset_id', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, to='network.assets')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('record_metadata_dynamic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_metadata_dynamic_link', models.FileField(blank=True, max_length=500, null=True, upload_to=network.models.records.record_metadata_dynamic_path)),
                ('metrics', models.FileField(blank=True, max_length=500, null=True, upload_to=network.models.records.record_metrics_path)),
                ('processing_type_id', models.ForeignKey(blank=True, db_column='processing_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.processing_types')),
                ('record_id', models.OneToOneField(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.records')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group_User_Linkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='network.groups')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='network.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('record_metadata_dynamic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_metadata_dynamic_link', models.FileField(blank=True, max_length=500, null=True, upload_to=network.models.records.record_metadata_dynamic_path)),
                ('metrics', models.FileField(blank=True, max_length=500, null=True, upload_to=network.models.records.record_metrics_path)),
                ('processing_type_id', models.ForeignKey(blank=True, db_column='processing_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.processing_types')),
                ('record_id', models.OneToOneField(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.records')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='object_metadata',
            name='sex_id',
            field=models.ForeignKey(blank=True, db_column='sex_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.sex'),
        ),
        migrations.AddField(
            model_name='object_metadata',
            name='species_id',
            field=models.ForeignKey(blank=True, db_column='species_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.species'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='FREE', max_length=50)),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTransfer',
            fields=[
                ('transfer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_files_expected', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('files_uploaded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dataset_id', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, to='network.datasets')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField()),
                ('dataset_id', models.ForeignKey(blank=True, db_column='dataset_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.datasets')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
